repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-json

  - repo: https://github.com/est31/cargo-udeps
    rev: v0.1.47
    hooks:
      - id: udeps
        args: ["--all-targets"]

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: format
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        args: ["--all", "--", "--check"]
      - id: clippy
        name: clippy
        description: lint
        entry: cargo clippy
        language: system
        types: [rust]
        args: ["--workspace", "--all-targets", "--", "-D", "warnings"]
        pass_filenames: false
