[package]
name = "nika"
version = "0.1.0"
authors = ["Magazzù Giuseppe"]
edition = "2021"
description = "Japanese learning CLI"
readme = "README.md"
repository = "https://github.com/saiteki-kai/nika"
license = "MIT"
default-run = "nika"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
confy = "0.5.1"
darkbird = "6.2.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.108"
tokio = "1.33.0"

[[bin]]
name = "nika"
path = "src/main.rs"

[[bin]]
name = "nika-updater"
path = "src/updater.rs"
