[package]
name = "nika"
version = "0.1.0"
authors = ["Magazzù Giuseppe"]
edition = "2021"
description = "Japanese learning CLI"
readme = "README.md"
repository = "https://github.com/saiteki-kai/nika"
license = "MIT"
default-run = "nika"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
clap = { version = "4.4.6", features = ["derive"] }
confy = "0.5.1"
darkbird = "6.2.0"
dirs = "5.0.1"
once_cell = "1.18.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = "1.0.190"
serde_derive = "1.0.190"
serde_json = "1.0.108"
tokio = "1.33.0"
tracing = "0.1.40"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.17"

[[bin]]
name = "nika"
path = "src/bin/main.rs"

[[bin]]
name = "nika-updater"
path = "src/bin/updater.rs"
