[package]
name = "nika"
version = "0.1.0"
edition = "2021"
authors = ["Magazzù Giuseppe"]
description = "Japanese learning CLI"
repository = "https://github.com/saiteki-kai/nika"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
confy = "0.5.1"
env_logger = "0.10.0"
serde = { version = "1.0.189", features = ["derive"] }
